question_data = [
    {"text":"modi is pm?",
     "answer": "True"},
{"text":"cm kcr?",
     "answer": "False"},
{"text":"god of crickek sachin?",
     "answer": "True"},
{"text":"king is vk?",
     "answer": "True"},
{"text":"captain cool is msd?",
     "answer": "True"},
{"text":"pushpa is babu?",
     "answer": "False"},
{"text":"ktr is it min?",
     "answer": "False"},
{"text":"i love veg?",
     "answer": "False"},
{"text":"chicken is not good?",
     "answer": "False"},
{"text":"mutton is too good?",
     "answer": "True"},
{"text":"fish is not nice?",
     "answer": "False"},
]

